version: '3.8'

services:
  extensions-service-database:
    image: mysql:8.0
    container_name: extensions-service-database
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: runtime_services
      MYSQL_PASSWORD: root1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
